import { db } from '../firebase';
import { collection, getDocs, addDoc, updateDoc, deleteDoc, doc, setDoc } from 'firebase/firestore';

const ENGINEERS_COLLECTION = 'engineers';
const ADMINS_COLLECTION = 'admins';

// Engineers
export const getEngineers = async () => {
    const snapshot = await getDocs(collection(db, ENGINEERS_COLLECTION));
    return snapshot.docs.map(doc => ({ id: doc.id, ...doc.data() }));
};

export const saveEngineer = async (engineer) => {
    if (engineer.id && engineer.id.length > 20) { // Assuming Firestore IDs are long strings if generated by Firestore, or we check if it exists
        // However, the app uses 'id' property. If it's a new one it might have a temp ID.
        // If the ID looks like it came from Firestore (20 chars), update. 
        // Or better, we always try to update if we have an ID that matches a document.
        // For simplicity, let's treat 'save' as 'upsert' but we need to know if it's new.

        // In the App.js logic, new engineers get `Date.now().toString()` as ID.
        // We can check if the ID is numeric (created by Date.now()) or string (Firestore).
        // Actually, let's just use setDoc if we want to control the ID, or addDoc if we want Firestore to generate it.
        // But to keep consistency with the UI that expects an ID immediately, we might have to handle this.

        // Strategy:
        // 1. If ID is NOT from Firestore (e.g. created locally with Date.now()), addDoc -> get new ID -> update local state.
        // 2. If ID IS from Firestore using it to update.

        // Let's rely on the assumption: if we are Editing, we pass the ID. If creating, we might pass a temp ID or no ID.

        try {
            const docRef = doc(db, ENGINEERS_COLLECTION, engineer.id);
            // Check if it's a valid Firestore ID or our temp ID. 
            // If it's our temp ID (Date.now()), we should probably `addDoc` instead to get a real ID.

            // Simplified approach for this migration:
            // Always setDoc if we have an ID, merging.
            await setDoc(docRef, engineer, { merge: true });
            return engineer.id;
        } catch (e) {
            console.error("Error saving engineer: ", e);
            throw e;
        }
    } else {
        // Create new
        const docRef = await addDoc(collection(db, ENGINEERS_COLLECTION), engineer);
        return docRef.id;
    }
};

export const deleteEngineer = async (id) => {
    await deleteDoc(doc(db, ENGINEERS_COLLECTION, id));
};


// Admins
export const getAdmins = async () => {
    const snapshot = await getDocs(collection(db, ADMINS_COLLECTION));
    return snapshot.docs.map(doc => ({ id: doc.id, ...doc.data() }));
};

export const saveAdmin = async (admin) => {
    if (admin.id) {
        const docRef = doc(db, ADMINS_COLLECTION, admin.id);
        await setDoc(docRef, admin, { merge: true });
        return admin.id;
    } else {
        const docRef = await addDoc(collection(db, ADMINS_COLLECTION), admin);
        return docRef.id;
    }
};

export const deleteAdmin = async (id) => {
    await deleteDoc(doc(db, ADMINS_COLLECTION, id));
};
